src = head.s
obj = head.o

# 这个程序被装载到的程序的地址
address = 0x1000

CFLAGS=-I.

kernelobj = head.o main.o 

all:main

%.o:%.c
	gcc -nostdinc -fno-pie $(CFLAGS) -c $< -m32 -o  $@

head.o:head.s entry.s
	nasm -f elf -o $@ $<

main:$(kernelobj)
	ld -s -m elf_i386 -o kernel.bin -Ttext $(address) $(kernelobj)

clean:
	-rm -f $(obj) $(elf) $(boot) $(kernelobj) kernel.bin